In [96]:
#se debe instalar ipyleaflet, mpu, openpyxl

import ipyleaflet
import mpu
import pandas as pd
import numpy as np
from ipyleaflet import Map, basemaps, Marker, AwesomeIcon, Icon

In [228]:
#Arma el Diccionario de Estaciones Linea A
estaciones = [
        {
    'id' : 1,
    'nombre' : 'Plaza de Mayo',
    'latitud' : -34.608861, 
    'longitud' : -58.370833
    },
    {
    'id' : 2,
    'nombre' : 'Peru',
    'latitud' : -34.608347, 
    'longitud' : -58.3743504
    },
    {
    'id' : 3,
    'nombre' : 'Piedras',
    'latitud' : -34.608910, 
    'longitud' : -58.379116
    },
    {
    'id' : 7,
    'nombre' : 'Pasco',
    'latitud' : -34.609275,
    'longitud' : -58.398412
    },
    {
    'id' : 9,
    'nombre' : 'Plaza Miserere',
    'latitud' : -34.6095038,
    'longitud' : -58.4068373
    },
    {
    'id' : 12,
    'nombre' : 'Rio de Janeiro',
    'latitud' : -34.6148813,
    'longitud' : -58.429314
    },
]

## Lectura del dataset Original de Properati

In [15]:
df_properati = pd.read_csv('properati.csv')

## Genera df solo para Capital

In [20]:
df_capital = df_properati[df_properati["state_name"] == "Capital Federal"]
df_capital.shape

(32316, 26)

In [31]:
Barrios = df_capital["place_name"].value_counts()

## Corrige ortografia de Barrios y mapea Barrios Inexistentes

In [64]:
df_reemplazo_barrios = pd.read_csv('reemplazos_barrios.csv')
df_reemplazo_barrios

            from              to
0  Villa Ortuzar   Villa Ortúzar
1  San Cristobal   San Cristóbal
2   Barrio Norte        Recoleta
3       Congreso       Balvanera

In [83]:
# df_capital["place_name"].replace(df_reemplazo_barrios["from"], df_reemplazo_barrios["to"], inplace=True)
df_capital["place_name"].replace(['San Cristobal','Barrio Norte', 'Centro / Microcentro'], ['San Cristóbal','Recoleta', 'Monserrat'], inplace=True)

In [84]:
barrios_conv = df_capital["place_name"].value_counts()

## Lee el archivo de Mapping de Barrios por Comuna

In [79]:
df_barrios_comuna = pd.read_csv("Barrios_x_Comuna_vsc_utf8.csv")

## Merge de df de Barrios de Capital con Comunas

In [80]:
comb = pd.merge(df_capital, df_barrios_comuna, how='left', left_on='place_name', right_on='Barrio')
del comb["description"]
del comb["title"]
del comb["properati_url"]
del comb["image_thumbnail"]

In [82]:
comb["Comuna"].isna().sum()

3835

## Enumera los Barrrios por los que atraviesa la Linea A

In [87]:
barrios_linea_a = pd.Series(['Monserrat', 'Balvanera', 'Almagro', 'Caballito'])
barrios_linea_a

0    Monserrat
1    Balvanera
2      Almagro
3    Caballito
dtype: object

## Filtra el df de Capital por los Barrios definidos

In [133]:
comb2 = comb[comb['Barrio'].isin(barrios_linea_a)]
comb2.shape

(3811, 24)

## Elimina los Registros sin lat-long

In [189]:
comb3 = comb2[comb2['lat-lon'].notna()]

In [190]:
comb3.shape
comb3.head(5)

,Unnamed: 0,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,...,price_aprox_usd,surface_total_in_m2,surface_covered_in_m2,price_usd_per_m2,price_per_m2,floor,rooms,expenses,Barrio,Comuna
14,48,sell,apartment,Balvanera,|Argentina|Capital Federal|Balvanera|,Argentina,Capital Federal,6693228.0,"-34.6096748,-58.3986588",-34.609675,...,240000.0,141.0,124.0,1702.127660,1935.483871,NaN,5.0,NaN,Balvanera,Comuna-3
16,52,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6222111,-58.4391283",-34.622211,...,110000.0,50.0,50.0,2200.000000,2200.000000,NaN,3.0,NaN,Caballito,Comuna-6
17,53,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6238943143,-58.4468606529",-34.623894,...,170500.0,100.0,46.0,1705.000000,3706.521739,NaN,2.0,NaN,Caballito,Comuna-6
18,54,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,220410.0,81.0,75.0,2721.111111,2938.800000,NaN,3.0,NaN,Caballito,Comuna-6
19,55,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,222780.0,81.0,75.0,2750.370370,2970.400000,NaN,3.0,NaN,Caballito,Comuna-6

## Calcula las distancias de cada Propiedad hasta las 17 estaciones

In [191]:
estacion_01_lat = -34.608861
estacion_01_lon = -58.370833

estacion_03_lat = -34.608910
estacion_03_lon = -58.379116

estacion_07_lat = -34.609275
estacion_07_lon = -58.398412


comb3['distancia_01'] = comb3[['lat','lon']].apply(lambda comb3: distancia(comb3['lat'],comb3['lon'],estacion_01_lat,estacion_01_lon),axis=1)
comb3['distancia_03'] = comb3[['lat','lon']].apply(lambda comb3: distancia(comb3['lat'],comb3['lon'],estacion_03_lat,estacion_03_lon),axis=1)
comb3['distancia_07'] = comb3[['lat','lon']].apply(lambda comb3: distancia(comb3['lat'],comb3['lon'],estacion_07_lat,estacion_07_lon),axis=1)

In [192]:
comb3.head(3)

,Unnamed: 0,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,...,price_usd_per_m2,price_per_m2,floor,rooms,expenses,Barrio,Comuna,distancia_01,distancia_03,distancia_07
14,48,sell,apartment,Balvanera,|Argentina|Capital Federal|Balvanera|,Argentina,Capital Federal,6693228.0,"-34.6096748,-58.3986588",-34.609675,...,1702.12766,1935.483871,NaN,5.0,NaN,Balvanera,Comuna-3,2.548179,1.790545,0.049865
16,52,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6222111,-58.4391283",-34.622211,...,2200.00000,2200.000000,NaN,3.0,NaN,Caballito,Comuna-6,6.423680,5.687485,3.994014
17,53,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6238943143,-58.4468606529",-34.623894,...,1705.00000,3706.521739,NaN,2.0,NaN,Caballito,Comuna-6,7.155333,6.419351,4.722174

In [193]:
comb3.shape

(3811, 27)

## Elimina los registros que no tengan el precio del m2 calculado

In [194]:
comb3_5 = comb3[comb3['price_usd_per_m2'].notna()]

In [195]:
comb3_5.shape

(2834, 27)

In [219]:
comb4 = comb3_5[comb3_5.index < 150]
comb4

,Unnamed: 0,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,...,price_usd_per_m2,price_per_m2,floor,rooms,expenses,Barrio,Comuna,distancia_01,distancia_03,distancia_07
14,48,sell,apartment,Balvanera,|Argentina|Capital Federal|Balvanera|,Argentina,Capital Federal,6693228.0,"-34.6096748,-58.3986588",-34.609675,...,1702.127660,1935.483871,NaN,5.0,NaN,Balvanera,Comuna-3,2.548179,1.790545,0.049865
16,52,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6222111,-58.4391283",-34.622211,...,2200.000000,2200.000000,NaN,3.0,NaN,Caballito,Comuna-6,6.423680,5.687485,3.994014
17,53,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6238943143,-58.4468606529",-34.623894,...,1705.000000,3706.521739,NaN,2.0,NaN,Caballito,Comuna-6,7.155333,6.419351,4.722174
18,54,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,2721.111111,2938.800000,NaN,3.0,NaN,Caballito,Comuna-6,6.996984,6.253577,4.532461
19,55,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,2750.370370,2970.400000,NaN,3.0,NaN,Caballito,Comuna-6,6.996984,6.253577,4.532461
21,59,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6287865,-58.4277832",-34.628786,...,1542.857143,1611.940299,NaN,3.0,NaN,Caballito,Comuna-6,5.662820,4.971706,3.454091
60,230,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.610435,-58.443029",-34.610435,...,2816.455696,2889.610390,NaN,5.0,NaN,Caballito,Comuna-6,6.609548,5.851643,4.085283
61,231,sell,PH,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.56910735,-58.4084898",-34.569107,...,1941.176471,1941.176471,NaN,4.0,NaN,Almagro,Comuna-5,5.605594,5.178643,4.560716
107,379,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6064821857,-58.4584048805",-34.606482,...,2303.571429,2580.000000,NaN,1.0,NaN,Caballito,Comuna-6,8.018954,7.261546,5.499318
111,384,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6098063,-58.4547167",-34.609806,...,2166.666667,2459.459459,NaN,1.0,NaN,Caballito,Comuna-6,7.677613,6.919563,5.153236
114,388,sell,apartment,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.6096938,-58.4198185",-34.609694,...,2727.272727,2916.666667,NaN,4.0,NaN,Almagro,Comuna-5,4.484029,3.726044,1.959636
115,389,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6040507,-58.4324956",-34.604051,...,1775.000000,1994.382022,NaN,5.0,NaN,Caballito,Comuna-6,5.668743,4.915168,3.173004
120,405,sell,apartment,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.6176909,-58.4228255",-34.617691,...,2142.857143,2553.191489,NaN,3.0,NaN,Almagro,Comuna-5,4.858286,4.117471,2.422240
121,411,sell,apartment,Monserrat,|Argentina|Capital Federal|Monserrat|,Argentina,Capital Federal,3430570.0,"-34.6130871,-58.3813599",-34.613087,...,2000.000000,2000.000000,NaN,2.0,NaN,Monserrat,Comuna-1,1.071884,0.507843,1.617090

In [220]:
comb4.shape

(14, 27)

In [221]:
# comb4['quantile'] = pd.qcut(comb4['price_usd_per_m2'], 4, labels=["muy bajo", "bajo", "medio", "alto"])
comb4['quantile'] = pd.qcut(comb4['price_usd_per_m2'], 4, labels=False)
comb4

/Users/marianobonilla/opt/anaconda3/envs/ipyleaflet/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Unnamed: 0,operation,property_type,place_name,place_with_parent_names,country_name,state_name,geonames_id,lat-lon,lat,...,price_per_m2,floor,rooms,expenses,Barrio,Comuna,distancia_01,distancia_03,distancia_07,quantile
14,48,sell,apartment,Balvanera,|Argentina|Capital Federal|Balvanera|,Argentina,Capital Federal,6693228.0,"-34.6096748,-58.3986588",-34.609675,...,1935.483871,NaN,5.0,NaN,Balvanera,Comuna-3,2.548179,1.790545,0.049865,0
16,52,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6222111,-58.4391283",-34.622211,...,2200.000000,NaN,3.0,NaN,Caballito,Comuna-6,6.423680,5.687485,3.994014,2
17,53,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6238943143,-58.4468606529",-34.623894,...,3706.521739,NaN,2.0,NaN,Caballito,Comuna-6,7.155333,6.419351,4.722174,0
18,54,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,2938.800000,NaN,3.0,NaN,Caballito,Comuna-6,6.996984,6.253577,4.532461,3
19,55,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6209278,-58.4458736",-34.620928,...,2970.400000,NaN,3.0,NaN,Caballito,Comuna-6,6.996984,6.253577,4.532461,3
21,59,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6287865,-58.4277832",-34.628786,...,1611.940299,NaN,3.0,NaN,Caballito,Comuna-6,5.662820,4.971706,3.454091,0
60,230,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.610435,-58.443029",-34.610435,...,2889.610390,NaN,5.0,NaN,Caballito,Comuna-6,6.609548,5.851643,4.085283,3
61,231,sell,PH,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.56910735,-58.4084898",-34.569107,...,1941.176471,NaN,4.0,NaN,Almagro,Comuna-5,5.605594,5.178643,4.560716,1
107,379,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6064821857,-58.4584048805",-34.606482,...,2580.000000,NaN,1.0,NaN,Caballito,Comuna-6,8.018954,7.261546,5.499318,2
111,384,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6098063,-58.4547167",-34.609806,...,2459.459459,NaN,1.0,NaN,Caballito,Comuna-6,7.677613,6.919563,5.153236,2
114,388,sell,apartment,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.6096938,-58.4198185",-34.609694,...,2916.666667,NaN,4.0,NaN,Almagro,Comuna-5,4.484029,3.726044,1.959636,3
115,389,sell,apartment,Caballito,|Argentina|Capital Federal|Caballito|,Argentina,Capital Federal,3435874.0,"-34.6040507,-58.4324956",-34.604051,...,1994.382022,NaN,5.0,NaN,Caballito,Comuna-6,5.668743,4.915168,3.173004,0
120,405,sell,apartment,Almagro,|Argentina|Capital Federal|Almagro|,Argentina,Capital Federal,3436397.0,"-34.6176909,-58.4228255",-34.617691,...,2553.191489,NaN,3.0,NaN,Almagro,Comuna-5,4.858286,4.117471,2.422240,1
121,411,sell,apartment,Monserrat,|Argentina|Capital Federal|Monserrat|,Argentina,Capital Federal,3430570.0,"-34.6130871,-58.3813599",-34.613087,...,2000.000000,NaN,2.0,NaN,Monserrat,Comuna-1,1.071884,0.507843,1.617090,1

In [229]:

## basic_map = Map(basemap=basemaps.Esri.DeLorme, center=(4.6097, -74.08), zoom=6)
basic_map = Map(basemap=basemaps.OpenStreetMap.Mapnik, center=(-34.60823238941058, -58.398160858739075), zoom=14)

icono_subte = Icon(icon_url='icono_subte.png', icon_size=[28, 28])

icon0 = AwesomeIcon(
    name='home',
    marker_color='green',
    icon_color='black',
    spin=False
)

icon1 = AwesomeIcon(
    name='home',
    marker_color='beige',
    icon_color='black',
    spin=False
)

icon2 = AwesomeIcon(
    name='home',
    marker_color='orange',
    icon_color='black',
    spin=False
)

icon3 = AwesomeIcon(
    name='home',
    marker_color='red',
    icon_color='black',
    spin=False
)

for estacion in estaciones:
    marker = Marker(location=(estacion['latitud'],estacion['longitud']), draggable=False, icon=icono_subte)
    basic_map.add_layer(marker);
    
# comb4.apply(marca_propiedad(), axis=1)
comb4[['lat','lon','quantile']].apply(lambda comb4: marca_propiedad(comb4['lat'],comb4['lon'],comb4['quantile']),axis=1)
    

display(basic_map)

Map(center=[-34.60823238941058, -58.398160858739075], controls=(ZoomControl(options=['position', 'zoom_in_text…

In [183]:
type(comb4['price_usd_per_m2'][14])

numpy.float64

In [172]:
comb4.to_csv("output.csv", index=False)

In [12]:
series_nulos_long = df_capital['lon'].isna()
series_nulos_long.value_counts()

False    23770
True      8546
Name: lon, dtype: int64

## Funciones

In [153]:
def distancia(lat1, long1, lat2, long2):
    return mpu.haversine_distance((lat1, long1), (lat2, long2))

In [207]:
def marca_propiedad(lat, long, quantile):
    if quantile == 0:
        icono_prop = icon0
    elif quantile == 1:
        icono_prop = icon1
    elif quantile == 2:
        icono_prop = icon2  
    else: 
        icono_prop = icon3
    marker = Marker(location=(lat,long), draggable=False, icon=icono_prop)
    basic_map.add_layer(marker)